#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

if xrandr | grep "HDMI1 connected"; then
	xrandr --output eDP1 --mode 1920x1080 --pos 0x1080 --rotate normal --output HDMI1 --primary --mode 1920x1080 --pos 0x0 --rotate normal & 
fi

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

export PATH="$HOME/.local/bin:$PATH"
# keybindings daemon
#sxhkd -c ~/.config/leftwm/sxhkd/sxhkdrc &
# diversity of apps to start
nm-applet &
#pamac-tray &
#xfce4-power-manager &
numlockx on &
blueberry-tray &
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#/usr/lib/xfce4/notifyd/xfce4-notifyd &
volumeicon &
dunst &
autostart &
unclutter &
#caffeine &
#firefox &
#thunar &
#dropbox &
#insync start &
#discord &
#spotify &

# Boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom --config $HOME/.config/leftwm/themes/current/picom.conf &> /dev/null &
  #picom --config $HOME/.config/leftwm/themes/current/picom.conf --experimental-backends &> /dev/null &
  #picom &> /dev/null &
  #picom --experimental-backends &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton --config $HOME/.config/leftwm/themes/current/compton.conf &> /dev/null &
fi

# Set the theme.ron config
leftwm command "LoadTheme $SCRIPTPATH/theme.ron"

# Set background
#if [ -x "$(command -v feh)" ]; then
#  feh --bg-fill "$SCRIPTPATH"/background.jpg
#fi

#mainbar
sleep 1
index=0
monitors=($(polybar -m | sed s/:.*//))
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  barname="mainbar$index"
  monitor=${monitors[index]} width=$(( width - 16 )) polybar -c "$SCRIPTPATH"/polybar.config $barname &> /dev/null &
  let index=index+1
done
